org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.206
loader_version_range=[1,)

## Mod Properties
mod_id=extendedae_plus
mod_name=ExtendedAE Plus
mod_version=1.21.1-1.0.9
mod_license=LGPL-3.0-or-later
mod_group_id=com.extendedae_plus
mod_authors=GaLicn, C-H716, XianYuFish001
mod_description=Extended ExtendedAE-Plus.