modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
description='''${mod_description}'''
logoFile = "icon.png"
logoBlur = false

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies."${mod_id}"]] #optional
modId="neoforge" #mandatory
type="required" #mandatory ["required", "optional", "incompatible", "discouraged"]
versionRange="[21.1.1,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="extendedae"
type="required"
versionRange="*"
ordering="AFTER"
side="BOTH"